Prep for next test. See notes
```
cp -R "$INPUT_SOURCE_FILE_PATH" "$CLONE_DIR/$INPUT_DESTINATION_FOLDER"
```
Got me (practice):
```
+ mktemp -d
+ CLONE_DIR=/tmp/tmp.nbkbbH
+ echo 'Clean up old references maybe'
+ git remote prune origin
Start
Clean up old references maybe
+ echo 'Cloning destination git repository'
Cloning destination git repository
+ git config --global user.email plocket@users.noreply.github.com
+ git config --global user.name plocket
+ git clone --single-branch --branch main https://***@github.com/plocket/tests-github-action-push.git /tmp/tmp.nbkbbH
Cloning into '/tmp/tmp.nbkbbH'...
+ ls -la /tmp/tmp.nbkbbH
total 12
drwx------    3 root     root          4096 Oct 19 17:59 .
drwxrwxrwt    1 root     root          4096 Oct 19 17:59 ..
drwxr-xr-x    8 root     root          4096 Oct 19 17:59 .git
Copying contents to to git repo
+ echo 'Copying contents to to git repo'
+ mkdir -p /tmp/tmp.nbkbbH/folder_test
+ cp -R output /tmp/tmp.nbkbbH/folder_test
+ cd /tmp/tmp.nbkbbH
total 16
+ ls -la
drwx------    4 root     root          4096 Oct 19 17:59 .
drwxrwxrwt    1 root     root          4096 Oct 19 17:59 ..
drwxr-xr-x    8 root     root          4096 Oct 19 17:59 .git
drwxr-xr-x    3 root     root          4096 Oct 19 17:59 folder_test
Adding git commit
+ echo 'Adding git commit'
+ git add .
+ git status
On branch main
Your branch is up to date with 'origin/main'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)
	new file:   folder_test/output/practice_file014.txt
+ git commit --message 'Update from https://github.com/plocket/docassemble-cucumber/commit/4d7752848823978a274104b3d290125ed72c1ff3'
[main 2d990aa] Update from https://github.com/plocket/docassemble-cucumber/commit/4d7752848823978a274104b3d290125ed72c1ff3
 1 file changed, 1 insertion(+)
 create mode 100644 folder_test/output/practice_file014.txt
Pushing git commit
+ echo 'Pushing git commit'
+ git push origin main
To https://github.com/plocket/tests-github-action-push.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 84ae3ea5fb46ac407984c53e8cf169bf3522a247 but expected 87c8ac3bce9c0682f6be8ab67c52e36cdbc20ecd)
error: failed to push some refs to 'https://***@github.com/plocket/tests-github-action-push.git'
```
on .gitignore

```
+ mktemp -d
+ CLONE_DIR=/tmp/tmp.coKhmL
+ echo 'Clean up old references maybe'
+ git remote prune origin
+ echo 'Cloning destination git repository'
Cloning destination git repository
+ git config --global user.email plocket@users.noreply.github.com
+ git config --global user.name plocket
+ git clone --single-branch --branch main https://***@github.com/plocket/tests-github-action-push.git /tmp/tmp.coKhmL
Cloning into '/tmp/tmp.coKhmL'...
+ ls -la /tmp/tmp.coKhmL
+ echo 'Copying contents to to git repo'
+ mkdir -p /tmp/tmp.coKhmL/
+ cp -R to_push /tmp/tmp.coKhmL/
total 12
drwx------    3 root     root          4096 Oct 19 17:59 .
drwxrwxrwt    1 root     root          4096 Oct 19 17:59 ..
drwxr-xr-x    8 root     root          4096 Oct 19 17:59 .git
Copying contents to to git repo
+ cd /tmp/tmp.coKhmL
+ ls -la
+ echo 'Adding git commit'
+ git add .
total 16
+ git status
+ git commit --message 'Update from https://github.com/plocket/docassemble-cucumber/commit/4d7752848823978a274104b3d290125ed72c1ff3'
drwx------    4 root     root          4096 Oct 19 17:59 .
drwxrwxrwt    1 root     root          4096 Oct 19 17:59 ..
drwxr-xr-x    8 root     root          4096 Oct 19 17:59 .git
drwxr-xr-x    2 root     root          4096 Oct 19 17:59 to_push
Adding git commit
On branch main
Your branch is up to date with 'origin/main'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)
	new file:   to_push/.gitignore
[main 415b07c] Update from https://github.com/plocket/docassemble-cucumber/commit/4d7752848823978a274104b3d290125ed72c1ff3
 1 file changed, 6 insertions(+)
+ echo 'Pushing git commit'
 create mode 100644 to_push/.gitignore
Pushing git commit
+ git push origin main
To https://github.com/plocket/tests-github-action-push.git
 ! [remote rejected] main -> main (cannot lock ref 'refs/heads/main': is at 84ae3ea5fb46ac407984c53e8cf169bf3522a247 but expected 87c8ac3bce9c0682f6be8ab67c52e36cdbc20ecd)
error: failed to push some refs to 'https://***@github.com/plocket/tests-github-action-push.git'
```
On package.json copied containing folder